admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

agence_front:
    resource: "@AgenceFrontBundle/Resources/config/routing.yml"
    prefix: /
dcs_rating:
    resource: "@DCSRatingBundle/Resources/config/routing.xml"
    prefix:   /