agence_front_controller:
    resource: "@AgenceFrontBundle/Controller"
    type:  annotation
    prefix:   /


user_index:
    path:     /
    defaults: { _controller: AgenceFrontBundle:Default:index }
user_accueil:
    path:     /site
    defaults: { _controller: AgenceFrontBundle:Default:accueil }