agence_front_controller:
    resource: "@AgenceFrontBundle/Controller"
    type:  annotation
    prefix:   /


user_index:
    path:     /
    defaults: { _controller: AgenceFrontBundle:Default:index }
user_accueil:
    path:     /site
    defaults: { _controller: AgenceFrontBundle:Default:accueil }
user_favoris:
    path:     /mesfavoris
    defaults: { _controller: AgenceFrontBundle:Default:mesFavoris }
recherche_index:
    path:    /offres/result
    defaults: { _controller: AgenceFrontBundle:Recherche:rechercheIndex }
    
offre_recherche:
     path:    /result
     defaults: { _controller: AgenceFrontBundle:Recherche:recherche }